In [1]:
import pandas as pd
import numpy as np
from datetime import *
from glob import glob

In [2]:
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

print(tf.__version__)

2.1.0

In [3]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import r2_score

In [4]:
import pylab as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

## Get data

In [5]:
with open('pipeline_data/steps.dat', 'r') as handle:
    steps = handle.readline().strip().split()

2020-11-07 2020-11-14

In [6]:
csv_fname = glob('pipeline_data/data_*-*-*_glm.csv')[0]
df = pd.read_csv(csv_fname, dtype={'fips': str}).set_index('fips')
df.head()

,case0,case1,case2,case3,case4,case5,case6,case7,case8,case9,...,death21_glm,death22_glm,death23_glm,death24_glm,death25_glm,death26_glm,death27_glm,death28_glm,death29_glm,death30_glm
fips,,,,,,,,,,,,,,,,,,,,,
01001,12.0,7.0,6.0,11.0,9.0,23.0,42.0,45.0,61.0,43.0,...,1.60,1.34,1.30,1.61,1.32,1.35,1.49,1.35,1.85,1.90
01003,29.0,37.0,43.0,38.0,34.0,35.0,38.0,19.0,10.0,21.0,...,2.95,2.52,2.18,2.64,2.37,2.13,2.23,2.61,3.23,3.17
01005,2.0,7.0,9.0,14.0,11.0,15.0,21.0,26.0,45.0,40.0,...,1.42,0.95,1.19,1.44,0.98,0.88,0.90,0.66,0.72,0.57
01007,4.0,9.0,13.0,8.0,8.0,3.0,5.0,8.0,14.0,5.0,...,0.76,0.58,0.65,0.80,0.61,0.66,0.76,0.58,0.78,0.83
01009,10.0,2.0,8.0,11.0,9.0,4.0,1.0,4.0,12.0,9.0,...,0.71,0.64,0.57,0.71,0.52,0.54,0.60,0.61,0.78,0.89

## Functions

In [7]:
class tfRegr:
    
    def __init__(self, 
                 epoch=100, 
                 verbose=False, 
                 validation_split=0.2, 
                 learning_rate=.1):
        
        self.normalizer = preprocessing.Normalization()
        self.ep = epoch
        self.vb = verbose
        self.vs = validation_split
        self.lr = learning_rate
    
    def fit(self, X, y):
        self.normalizer.adapt(X)

        self.model = tf.keras.Sequential([
            self.normalizer,
            layers.Dense(units=1)
        ])

        self.model.compile(
            optimizer=tf.optimizers.Adam(learning_rate=self.lr),
            loss='mean_absolute_error'
        )

        self.history = self.model.fit(
            X, y,
            epochs=self.ep,
            verbose=self.vb, # logging
            validation_split=self.vs # Calculate validation results on a fraction of the training data
        )
        return self.model

In [36]:
def predict(df, cur_idx):

    regrs = {
        'RF': RandomForestRegressor(min_samples_split=2), 
        'ET': ExtraTreesRegressor(min_samples_split=2), 
        'TF': tfRegr(),
    }
    
    cur = f'case{cur_idx}'

    glm = [f'case{cur_idx - 1}_glm', f'case{cur_idx}_glm'] 
    cols = [f'case{cur_idx - 1}'] + glm
    X, y = df[cols].values, df[cur].values 
    
    
    for name, regr in regrs.items():
        regr = regr.fit(X, y)

        #================ Evaluation ===============START
        y_pred = regr.predict(X).flatten()
        r2 = r2_score(y, y_pred)
        rmse = np.sqrt(((y - y_pred) ** 2).mean())
        print(f'\t{name}: r2 = {r2:.3f}, rmse = {rmse:.3f}')
        #================ Evaluation ===============START
        
        cols = [cur] + glm
        df[cur + f'_{name}_1'] = regr.predict(df[cols].values).flatten()
        
        cols = [cur + f'_{name}_1'] + glm
        df[cur + f'_{name}_2'] = regr.predict(df[cols].values).flatten()
    
    prd_cols_1 = [col for col in df.columns if col.endswith('_1')]
    prd_cols_2 = [col for col in df.columns if col.endswith('_2')]
    prd_1 = df[prd_cols_1].mean(axis=1).values
    prd_2 = df[prd_cols_2].mean(axis=1).values
    
    df.drop(prd_cols_1 + prd_cols_2, axis=1, inplace=True)
    
    return prd_1, prd_2

## Forecast Runs

In [37]:
cur_idx = len(steps) - 1

num_runs = 100
prds_1, prds_2 = [], []

for r in range(num_runs):
    print(f'run = {r}')
    prd_1, prd_2 = predict(df, cur_idx)
    prds_1.append(prd_1)
    prds_2.append(prd_2)

run = 0
	RF: r2 = 0.948, rmse = 120.588
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.400
run = 1
	RF: r2 = 0.933, rmse = 136.756
	ET: r2 = 1.000, rmse = 0.154
	TF: r2 = 0.865, rmse = 194.342
run = 2
	RF: r2 = 0.960, rmse = 105.706
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.613
run = 3
	RF: r2 = 0.961, rmse = 104.694
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.639
run = 4
	RF: r2 = 0.973, rmse = 86.758
	ET: r2 = 1.000, rmse = 0.045
	TF: r2 = 0.866, rmse = 194.059
run = 5
	RF: r2 = 0.955, rmse = 112.979
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.865, rmse = 194.678
run = 6
	RF: r2 = 0.978, rmse = 78.543
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.919
run = 7
	RF: r2 = 0.985, rmse = 64.791
	ET: r2 = 1.000, rmse = 0.193
	TF: r2 = 0.865, rmse = 194.688
run = 8
	RF: r2 = 0.951, rmse = 117.057
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.866, rmse = 193.979
run = 9
	RF: r2 = 0.985, rmse = 65.196
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 195.028
run = 10
	RF: r2 = 0.962, rmse = 102.655
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.202
run = 11
	RF: r2 = 0.942, rmse = 127.343
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.865, rmse = 194.814
run = 12
	RF: r2 = 0.975, rmse = 83.102
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.549
run = 13
	RF: r2 = 0.974, rmse = 85.735
	ET: r2 = 1.000, rmse = 0.083
	TF: r2 = 0.864, rmse = 195.567
run = 14
	RF: r2 = 0.973, rmse = 87.725
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.505
run = 15
	RF: r2 = 0.973, rmse = 87.441
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.337
run = 16
	RF: r2 = 0.980, rmse = 74.192
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.866, rmse = 194.159
run = 17
	RF: r2 = 0.976, rmse = 82.487
	ET: r2 = 1.000, rmse = 0.075
	TF: r2 = 0.866, rmse = 194.273
run = 18
	RF: r2 = 0.981, rmse = 73.889
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.862, rmse = 196.579
run = 19
	RF: r2 = 0.982, rmse = 72.056
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.689
run = 20
	RF: r2 = 0.978, rmse = 78.985
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.090
run = 21
	RF: r2 = 0.982, rmse = 70.755
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.865, rmse = 194.588
run = 22
	RF: r2 = 0.964, rmse = 100.954
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.864, rmse = 195.447
run = 23
	RF: r2 = 0.971, rmse = 90.996
	ET: r2 = 1.000, rmse = 0.154
	TF: r2 = 0.865, rmse = 194.899
run = 24
	RF: r2 = 0.960, rmse = 105.497
	ET: r2 = 1.000, rmse = 0.060
	TF: r2 = 0.864, rmse = 195.228
run = 25
	RF: r2 = 0.972, rmse = 89.077
	ET: r2 = 1.000, rmse = 0.023
	TF: r2 = 0.864, rmse = 195.457
run = 26
	RF: r2 = 0.974, rmse = 86.246
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.864, rmse = 195.134
run = 27
	RF: r2 = 0.971, rmse = 89.750
	ET: r2 = 1.000, rmse = 0.154
	TF: r2 = 0.865, rmse = 194.510
run = 28
	RF: r2 = 0.966, rmse = 98.371
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.748
run = 29
	RF: r2 = 0.974, rmse = 85.252
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.865, rmse = 194.463
run = 30
	RF: r2 = 0.957, rmse = 110.290
	ET: r2 = 1.000, rmse = 0.020
	TF: r2 = 0.864, rmse = 195.231
run = 31
	RF: r2 = 0.971, rmse = 90.210
	ET: r2 = 1.000, rmse = 0.037
	TF: r2 = 0.866, rmse = 193.665
run = 32
	RF: r2 = 0.958, rmse = 108.468
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.182
run = 33
	RF: r2 = 0.977, rmse = 80.297
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.866, rmse = 194.211
run = 34
	RF: r2 = 0.956, rmse = 111.464
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.865, rmse = 194.587
run = 35
	RF: r2 = 0.978, rmse = 77.981
	ET: r2 = 1.000, rmse = 0.020
	TF: r2 = 0.866, rmse = 194.128
run = 36
	RF: r2 = 0.953, rmse = 115.045
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 195.034
run = 37
	RF: r2 = 0.941, rmse = 128.873
	ET: r2 = 1.000, rmse = 0.048
	TF: r2 = 0.864, rmse = 195.108
run = 38
	RF: r2 = 0.966, rmse = 97.167
	ET: r2 = 1.000, rmse = 0.125
	TF: r2 = 0.865, rmse = 194.745
run = 39
	RF: r2 = 0.967, rmse = 96.532
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.783
run = 40
	RF: r2 = 0.968, rmse = 95.249
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.767
run = 41
	RF: r2 = 0.967, rmse = 96.933
	ET: r2 = 1.000, rmse = 0.020
	TF: r2 = 0.866, rmse = 194.032
run = 42
	RF: r2 = 0.972, rmse = 88.382
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.866, rmse = 194.315
run = 43
	RF: r2 = 0.985, rmse = 65.909
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.545
run = 44
	RF: r2 = 0.950, rmse = 118.196
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.385
run = 45
	RF: r2 = 0.970, rmse = 91.401
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.863, rmse = 196.018
run = 46
	RF: r2 = 0.966, rmse = 97.111
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.623
run = 47
	RF: r2 = 0.973, rmse = 87.278
	ET: r2 = 1.000, rmse = 0.075
	TF: r2 = 0.865, rmse = 194.694
run = 48
	RF: r2 = 0.973, rmse = 86.404
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.844
run = 49
	RF: r2 = 0.964, rmse = 101.013
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.162
run = 50
	RF: r2 = 0.964, rmse = 101.031
	ET: r2 = 1.000, rmse = 0.130
	TF: r2 = 0.864, rmse = 195.140
run = 51
	RF: r2 = 0.978, rmse = 77.901
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.214
run = 52
	RF: r2 = 0.969, rmse = 93.360
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.865, rmse = 194.867
run = 53
	RF: r2 = 0.959, rmse = 107.398
	ET: r2 = 1.000, rmse = 0.078
	TF: r2 = 0.866, rmse = 194.090
run = 54
	RF: r2 = 0.972, rmse = 88.197
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.406
run = 55
	RF: r2 = 0.961, rmse = 104.245
	ET: r2 = 1.000, rmse = 0.020
	TF: r2 = 0.865, rmse = 194.438
run = 56
	RF: r2 = 0.964, rmse = 99.997
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.865, rmse = 194.570
run = 57
	RF: r2 = 0.973, rmse = 86.492
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.866, rmse = 193.941
run = 58
	RF: r2 = 0.963, rmse = 101.853
	ET: r2 = 1.000, rmse = 0.060
	TF: r2 = 0.865, rmse = 194.619
run = 59
	RF: r2 = 0.979, rmse = 75.878
	ET: r2 = 1.000, rmse = 0.150
	TF: r2 = 0.865, rmse = 194.787
run = 60
	RF: r2 = 0.961, rmse = 104.029
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.207
run = 61
	RF: r2 = 0.973, rmse = 87.211
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.636
run = 62
	RF: r2 = 0.984, rmse = 66.633
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.962
run = 63
	RF: r2 = 0.966, rmse = 97.440
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.865, rmse = 194.963
run = 64
	RF: r2 = 0.974, rmse = 85.729
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.454
run = 65
	RF: r2 = 0.970, rmse = 92.380
	ET: r2 = 1.000, rmse = 0.155
	TF: r2 = 0.865, rmse = 194.372
run = 66
	RF: r2 = 0.971, rmse = 90.169
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.866, rmse = 194.156
run = 67
	RF: r2 = 0.964, rmse = 99.860
	ET: r2 = 1.000, rmse = 0.486
	TF: r2 = 0.865, rmse = 194.605
run = 68
	RF: r2 = 0.978, rmse = 78.338
	ET: r2 = 1.000, rmse = 0.156
	TF: r2 = 0.866, rmse = 194.301
run = 69
	RF: r2 = 0.969, rmse = 92.896
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.593
run = 70
	RF: r2 = 0.963, rmse = 102.284
	ET: r2 = 1.000, rmse = 0.076
	TF: r2 = 0.865, rmse = 194.692
run = 71
	RF: r2 = 0.963, rmse = 102.008
	ET: r2 = 1.000, rmse = 0.135
	TF: r2 = 0.865, rmse = 194.423
run = 72
	RF: r2 = 0.964, rmse = 101.175
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.364
run = 73
	RF: r2 = 0.973, rmse = 87.595
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.439
run = 74
	RF: r2 = 0.957, rmse = 109.659
	ET: r2 = 1.000, rmse = 0.151
	TF: r2 = 0.866, rmse = 193.982
run = 75
	RF: r2 = 0.960, rmse = 106.498
	ET: r2 = 1.000, rmse = 0.154
	TF: r2 = 0.864, rmse = 195.553
run = 76
	RF: r2 = 0.972, rmse = 89.133
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.390
run = 77
	RF: r2 = 0.970, rmse = 92.440
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.865, rmse = 194.884
run = 78
	RF: r2 = 0.952, rmse = 116.177
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.697
run = 79
	RF: r2 = 0.952, rmse = 116.533
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.864, rmse = 195.397
run = 80
	RF: r2 = 0.955, rmse = 112.362

	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.209
run = 81
	RF: r2 = 0.978, rmse = 77.926
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.863, rmse = 196.075
run = 82
	RF: r2 = 0.984, rmse = 66.159
	ET: r2 = 1.000, rmse = 0.150
	TF: r2 = 0.866, rmse = 193.726
run = 83
	RF: r2 = 0.967, rmse = 95.758
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.864, rmse = 195.451
run = 84
	RF: r2 = 0.956, rmse = 111.340
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.865, rmse = 194.447
run = 85
	RF: r2 = 0.972, rmse = 89.001
	ET: r2 = 1.000, rmse = 0.052
	TF: r2 = 0.864, rmse = 195.512
run = 86
	RF: r2 = 0.951, rmse = 117.296
	ET: r2 = 1.000, rmse = 0.035
	TF: r2 = 0.865, rmse = 194.949
run = 87
	RF: r2 = 0.964, rmse = 101.126
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.866, rmse = 194.034
run = 88
	RF: r2 = 0.963, rmse = 101.364
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.425
run = 89
	RF: r2 = 0.971, rmse = 90.544
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.949
run = 90
	RF: r2 = 0.976, rmse = 82.465
	ET: r2 = 1.000, rmse = 0.028
	TF: r2 = 0.864, rmse = 195.125
run = 91
	RF: r2 = 0.954, rmse = 113.525
	ET: r2 = 1.000, rmse = 0.041
	TF: r2 = 0.865, rmse = 194.715
run = 92
	RF: r2 = 0.971, rmse = 90.628
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.945
run = 93
	RF: r2 = 0.984, rmse = 68.001
	ET: r2 = 1.000, rmse = 0.020
	TF: r2 = 0.865, rmse = 194.863
run = 94
	RF: r2 = 0.979, rmse = 76.454
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.585
run = 95
	RF: r2 = 0.973, rmse = 87.713
	ET: r2 = 1.000, rmse = 0.083
	TF: r2 = 0.865, rmse = 194.412
run = 96
	RF: r2 = 0.963, rmse = 102.092
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.866, rmse = 194.315
run = 97
	RF: r2 = 0.977, rmse = 80.258
	ET: r2 = 1.000, rmse = 0.000
	TF: r2 = 0.865, rmse = 194.552
run = 98
	RF: r2 = 0.960, rmse = 105.519
	ET: r2 = 1.000, rmse = 0.130
	TF: r2 = 0.867, rmse = 193.550
run = 99
	RF: r2 = 0.976, rmse = 81.866
	ET: r2 = 1.000, rmse = 0.075
	TF: r2 = 0.866, rmse = 193.927

In [43]:
df_county_prd_1 = pd.DataFrame(data=np.array(prds_1).T, index=df.index, columns=range(num_runs))
df_county_prd_2 = pd.DataFrame(data=np.array(prds_2).T, index=df.index, columns=range(num_runs))

## Prepare for submission

In [ ]:
cur_dt = datetime.strptime(steps[cur_idx], '%Y-%m-%d')
nxt_dt_1 = (cur_dt + timedelta(days=7)).date()
nxt_dt_2 = (cur_dt + timedelta(days=14)).date()
print(nxt_dt_1, nxt_dt_2)

qs = [.025, .1, .25, .5, .75, .9, .975]

### points

In [58]:
df_county_point_1 = df_county_prd_1.mean(axis=1).reset_index()\
    .rename(columns={0: 'value', 'fips': 'location'})
df_county_point_1['type'] = 'point'
df_county_point_1['quantile'] = 'NA'


df_county_quantile_1 = df_county_prd_1.quantile(qs, axis=1).T.reset_index()\
    .melt(id_vars=['fips']).sort_values('fips')\
    .rename(columns={'fips': 'location', 'variable': 'quantile'})
df_county_quantile_1['type'] = 'quantile'

df_forecast_1 = pd.concat

df_county_quantile_1['target'] = '1 wk ahead inc case'


df_county_point_2 = df_county_prd_2.mean(axis=1).reset_index()\
    .rename(columns={0: 'value', 'fips': 'location'})
df_county_point_2['type'] = 'point'
df_county_point_2['target'] = '2 wk ahead inc case'
df_county_point_2['quantile'] = 'NA'
df_county_point_2.head()

  location       value   type               target quantile
0    01001  147.804935  point  2 wk ahead inc case       NA
1    01003  373.260547  point  2 wk ahead inc case       NA
2    01005   37.836025  point  2 wk ahead inc case       NA
3    01007   57.688430  point  2 wk ahead inc case       NA
4    01009  152.562126  point  2 wk ahead inc case       NA

### quantiles

In [59]:
qs = [.025, .1, .25, .5, .75, .9, .975]
df_county_quantile_1 = df_county_prd_1.quantile(qs, axis=1).T.reset_index()\
    .melt(id_vars=['fips']).sort_values('fips')\
    .rename(columns={'fips': 'location', 'variable': 'quantile'})
df_county_quantile_1['type'] = 'quantile'
df_county_quantile_1['target'] = '1 wk ahead inc case'

df_county_quantile_2 = df_county_prd_2.quantile(qs, axis=1).T.reset_index()\
    .melt(id_vars=['fips']).sort_values('fips')\
    .rename(columns={'fips': 'location', 'variable': 'quantile'})
df_county_quantile_2['type'] = 'quantile'
df_county_quantile_2['target'] = '2 wk ahead inc case'

In [64]:
df_forecast = pd.concat([
    df_county_point_1,
    df_county_point_2, 
    df_county_quantile_1, 
    df_county_quantile_2
]).reset_index(drop=True)

  location quantile               target   type       value
0    01001       NA  1 wk ahead inc case  point  138.509799
1    01003       NA  1 wk ahead inc case  point  344.258966
2    01005       NA  1 wk ahead inc case  point   42.213962
3    01007       NA  1 wk ahead inc case  point   53.129535
4    01009       NA  1 wk ahead inc case  point  148.942071

In [27]:
cur_dt = datetime.strptime(steps[cur_idx], '%Y-%m-%d')
nxt_dt_1 = (cur_dt + timedelta(days=7)).date()
nxt_dt_2 = (cur_dt + timedelta(days=14)).date()
print(nxt_dt_1, nxt_dt_2)

2020-11-07 2020-11-14